name: Integration

on:
  push:
    branches:
      - "main"
  pull_request:
  merge_group:

jobs:
  version:
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: get_version
        uses: paulhatch/semantic-version@v5.4.0

  print:
    runs-on: ubuntu-latest
    needs: [version]
    steps:
      - name: "Print version"
        run: echo ${{needs.version.outputs.version}}

  tag:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: [version]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Tag
        run: |
          git tag v${{needs.version.outputs.version}}
          git push --tags